[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = ""

[functions]
  external_node_modules = ["express", "cookie-parser", "cors", "dotenv", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200